// @ts-check
//
// Offline-bundle build config (#V10 — Docs offline ZIP).
//
// Spread-imports the production docusaurus.config.js and overrides only what is
// needed to produce a bundle that browses correctly when opened directly from
// the filesystem (file://), with no web server:
//
//   • experimental_router 'hash' — Docusaurus's built-in offline router
//     (facebook/docusaurus#9859). Emits a single-page app whose internal
//     navigation uses URL hashes (#/intro) and — critically — makes all
//     asset/link URLs relative, so they resolve from the unzipped folder under
//     file://. This is the mechanism Docusaurus ships for offline .zip
//     distribution.
//   • baseUrl '/' — the hash router is documented to work best with NO sub-path
//     baseUrl (the production build uses '/docs/'); it handles relative paths
//     itself, and a sub-path baseUrl is a known source of hash-router bugs.
//   • drop local search — @easyops-cn/docusaurus-search-local fetches its index
//     at runtime in a Web Worker over the page origin, which browsers block
//     under file://. The offline bundle is intentionally browse-only; dropping
//     the theme also saves the ~4.4 MB index. (See docs/download-offline.md.)
//
// Invoked by scripts/build-offline-zip.js as:
//   docusaurus build --config docusaurus.offline.config.js --out-dir <temp>
// after the production build, so docs/api/*.md (generated by the prebuild hook)
// already exist when this runs.

import baseConfig from './docusaurus.config.js';

const SEARCH_THEME = '@easyops-cn/docusaurus-search-local';

/** @type {import('@docusaurus/types').Config} */
const offlineConfig = {
  ...baseConfig,
  baseUrl: '/',
  future: {
    ...(baseConfig.future || {}),
    experimental_router: 'hash',
  },
  themes: (baseConfig.themes || []).filter(function (t) {
    var name = Array.isArray(t) ? t[0] : t;
    return name !== SEARCH_THEME;
  }),
};

export default offlineConfig;
