// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // Main docs sidebar — autogenerated from the full docs tree.
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Standalone sidebar for the roadmap page.
  // roadmap.md sets `displayed_sidebar: roadmapSidebar` in its frontmatter
  // so Docusaurus treats it as "in" this sidebar, making only the Roadmap
  // navbar item active (not Docs) when visiting /docs/roadmap.
  roadmapSidebar: ['roadmap'],

  // Standalone sidebar for the support page.
  // support.md sets `displayed_sidebar: supportSidebar` in its frontmatter.
  supportSidebar: ['support'],

  // Tutorials sidebar — autogenerated from the tutorials/ directory.
  // Tutorial pages set `displayed_sidebar: tutorialsSidebar` so the Tutorials
  // navbar item stays active (not Docs) when reading a tutorial.
  tutorialsSidebar: [{type: 'autogenerated', dirName: 'tutorials'}],

  // Swig sidebar — autogenerated from the swig/ directory.
  // Swig pages set `displayed_sidebar: swigSidebar` so the Swig navbar item
  // stays active (not Docs) when reading a Swig page.
  swigSidebar: [{type: 'autogenerated', dirName: 'swig'}],
};

export default sidebars;
