#!/usr/bin/env node

/*
 * This file is part of the gina-io/docs repository.
 * Copyright (c) 2009-2026 Rhinostone <contact@gina.io>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * Pre-flight leak check for gina-io/docs.
 *
 * This package is `private: true` and never publishes to npm, so the gina
 * repo's `npm pack`-based check does not apply. Instead, this scan walks
 * `git ls-files` (the set of tracked paths) and fails the check if either:
 *
 *   1. Path-level: any local-tool configuration file or directory is in
 *      the git index (`CLAUDE.md`, `.claude/...`, `.claudeignore`, any
 *      future `claude*` file).
 *
 *   2. Content-level: any tracked text file contains a forbidden
 *      AI-attribution / marketing-style token. The narrow patterns avoid
 *      false-positives on the AI connector documentation (which legitimately
 *      names supported providers — see the allow-list reasoning in
 *      `CLAUDE.md` § HARD RULE — No local-tool / AI-attribution mentions).
 *
 * Run before every commit on `develop` and every push to `main`:
 *
 *     node scripts/check_no_local_leak.js
 *
 * Exit codes:
 *   0  — pack listing and contents are clean
 *   1  — leakage detected OR check itself errored (fail closed)
 */

var execSync = require('child_process').execSync;
var fs       = require('fs');

var PATH_PATTERN = /(^|\/)(CLAUDE\.md|\.claude[a-z]*)/i;

// Forbidden tokens — AI-attribution / marketing-style mentions.
// Patterns are deliberately narrow so the AI connector docs (which cite
// `anthropic://`, `@anthropic-ai/sdk`, `ANTHROPIC_API_KEY`, model IDs like
// `claude-opus-4-6`, and provider names in tab labels) do not trip them.
// These are product functionality, not attribution — see CLAUDE.md.
var CONTENT_TOKENS = [
    { name: 'attribution footer (Generated by Claude)', pattern: /generated by claude/i },
    { name: 'co-author line (Co-Authored-By: Claude)',  pattern: /co-?authored-?by[^\n]*claude/i },
    { name: 'attribution URL (claude.ai/code)',         pattern: /claude\.ai\/code/i },
    { name: 'attribution URL (claude.com/claude-code)', pattern: /claude\.com\/claude-code/i },
    { name: 'attribution emoji + Claude',               pattern: /🤖[^\n]*claude/i },
    { name: 'product-name marketing (Claude Desktop)',  pattern: /claude\s+desktop/i },
    { name: 'product-name marketing (Claude Code)',     pattern: /\bclaude\s+code\b/i }
];

// Heuristic: only read files that are likely text. Saves time on binary
// assets (images, fonts, compiled bundles) and prevents pattern matches
// from random byte sequences.
var TEXT_EXT = /\.(md|mdx|txt|json|js|mjs|cjs|ts|tsx|jsx|html|htm|css|sass|scss|less|sh|bash|zsh|yaml|yml|xml|svg|csv|d\.ts|conf|ini|toml|env|template)$/i;
var TEXT_BASENAME = /^(AUTHORS|LICENSE|COPYING|CHANGELOG|README|NOTICE|CONTRIBUTING|GOVERNANCE|Makefile|\.gitignore|\.eslintrc|\.editorconfig)(\.[^.]+)?$/;

// Scanner script contains the token patterns themselves — skip it to
// avoid self-matches. Future maintainers: add any new scanner files here.
var SELF_EXCLUDE = {
    'scripts/check_no_local_leak.js': true
};

// Files larger than this are skipped — production bundles and lockfiles
// don't warrant a byte-by-byte scan.
var MAX_SCAN_BYTES = 2 * 1024 * 1024;

function isTextPath(p) {
    if (TEXT_EXT.test(p)) return true;
    var base = p.split('/').pop();
    if (TEXT_BASENAME.test(base)) return true;
    return false;
}

function scanContent(path) {
    var stat;
    try { stat = fs.statSync(path); } catch (e) { return []; }
    if (!stat.isFile() || stat.size > MAX_SCAN_BYTES) return [];

    var content;
    try { content = fs.readFileSync(path, 'utf8'); } catch (e) { return []; }

    var hits = [];
    for (var i = 0; i < CONTENT_TOKENS.length; i++) {
        if (CONTENT_TOKENS[i].pattern.test(content)) {
            hits.push(CONTENT_TOKENS[i].name);
        }
    }
    return hits;
}

// Defense-in-depth: `.npmignore` must list every Claude-related path even
// though this package is currently `private: true` and never publishes.
// If `private: true` is ever dropped, the npm-pack leak rule kicks in
// instantly without `.npmignore` having to be re-discovered.
var REQUIRED_NPMIGNORE = [
    { pattern: /^CLAUDE\.md\s*$/m,     name: 'CLAUDE.md' },
    { pattern: /^\.claude\/\s*$/m,     name: '.claude/' },
    { pattern: /^\.claudeignore\s*$/m, name: '.claudeignore' }
];

function checkNpmignore() {
    var p = '.npmignore';
    if (!fs.existsSync(p)) {
        return ['.npmignore is missing — HARD RULE requires it to exist with Claude-related entries'];
    }
    var content;
    try { content = fs.readFileSync(p, 'utf8'); } catch (e) { return ['.npmignore — read failed: ' + e.message]; }

    var missing = [];
    for (var i = 0; i < REQUIRED_NPMIGNORE.length; i++) {
        if (!REQUIRED_NPMIGNORE[i].pattern.test(content)) {
            missing.push(REQUIRED_NPMIGNORE[i].name);
        }
    }
    if (missing.length > 0) {
        return ['.npmignore is missing required entries: ' + missing.join(', ')];
    }
    return [];
}

try {
    var raw = execSync('git ls-files', { stdio: ['ignore', 'pipe', 'pipe'] }).toString();
    var files = raw.split('\n').filter(function(l) { return l.length > 0; });

    var pathMatches = [];
    var contentMatches = [];
    var npmignoreErrors = checkNpmignore();

    for (var i = 0; i < files.length; i++) {
        var p = files[i];

        if (PATH_PATTERN.test(p)) {
            pathMatches.push(p);
        }

        if (isTextPath(p) && !SELF_EXCLUDE[p]) {
            var hits = scanContent(p);
            for (var k = 0; k < hits.length; k++) {
                contentMatches.push(p + ' — ' + hits[k]);
            }
        }
    }

    var failed = false;

    if (npmignoreErrors.length > 0) {
        console.error('[leak-scan] ERROR: .npmignore self-enforcement violation:');
        for (var n = 0; n < npmignoreErrors.length; n++) {
            console.error('  - ' + npmignoreErrors[n]);
        }
        console.error('[leak-scan] Add the missing entries to .npmignore (HARD RULE — see CLAUDE.md).');
        failed = true;
    }

    if (pathMatches.length > 0) {
        console.error('[leak-scan] ERROR: local-tool paths in git index:');
        for (var a = 0; a < pathMatches.length; a++) {
            console.error('  - ' + pathMatches[a]);
        }
        console.error('[leak-scan] Remove with: git rm --cached <path>');
        console.error('[leak-scan] If pushed: git filter-repo --invert-paths --path <path>');
        failed = true;
    }

    if (contentMatches.length > 0) {
        if (failed) console.error('');
        console.error('[leak-scan] ERROR: AI-attribution / marketing tokens in tracked content:');
        for (var b = 0; b < contentMatches.length; b++) {
            console.error('  - ' + contentMatches[b]);
        }
        console.error('[leak-scan] Scrub these files before committing.');
        console.error('[leak-scan] If already on the remote, see CLAUDE.md § public-surface remediation.');
        failed = true;
    }

    if (failed) {
        process.exit(1);
    }

    console.log('[leak-scan] OK: tracked paths and content are clean.');
    process.exit(0);
} catch (err) {
    console.error('[leak-scan] Check failed: ' + (err.message || err));
    console.error('[leak-scan] Failing closed — investigate.');
    process.exit(1);
}
